### ISSUE TITLE
Add Custom Video player

### ISSUE THREAD

**Issue by ch1ck3n-byte** [Yonle/ytmous#3]
maybe add a custom video player, like youtube's? that would be cool and siick.

**Comment by Yonle** [comment]
Maybe we're gonna use video.js for that.

**Comment by Yonle** [comment]
Seems like plyr.io is the best choice for that
(╯° □°） ╯︵ ┻━┻

**Comment by Yonle** [comment]
It's not released. Hope you enjoy it :^)

**Comment by ch1ck3n-byte** [comment]
yaay new version
