### ISSUE TITLE
Error: Status code: 404

### ISSUE THREAD

**Issue by Luchemiel** [Yonle/ytmous#9]
Hello, and thank you for this great input (ytmous),
I use it everyday.

Today i tried using it and it seaches the video but after i click on the vid thumbnail i get the error:

Error: Status code: 404

I have tried the mirrors here and the same issue.
Just reporting hoping for it to be back up as soon as it can.

Thank you again for this input it is helpfull.

**Comment by Yonle** [comment]
Hello. May you try host it yourself and repeat action (Watch some video) again?

If it works for you, It means a mirror that you recently visit that got 404 Error can be got ratelimited.

**Comment by Yonle** [comment]
@Luchemiel Also you may need to update your ytdl.

**Comment by Yonle** [comment]
You may need to see [this issue](https://github.com/fent/node-ytdl-core/issues/939) too as it's related with your problem.

**Comment by Yonle** [comment]
This issue is resolved now. All mirror should be able to ready-to-use.

Have a nice day with ytmous.
